### PR TITLE
✨ Support auto inactive

### PR DESCRIPTION
**Pull request by dmcnamara-eng**
Hello @achambers 

Wondering do these changes belong in trunk?

### CODE REVIEW

**Comment by nelstrom** [comment]
I'll add a little bit of context here. First up, here's [the documentation for the `auto_inactive` property](https://docs.github.com/en/rest/reference/repos#inactive-deployments).

I was motivated to make this change, because we started seeing our deployments being marked as inactive, like so:

Screenshot 2021-11-11 at 13 41 20

Roughly speaking, here's a sequence of events that could lead to this scenario:

* Drew publishes a branch called `drews-feature` to GitHub
* CI runs for the latest commit in `drews-feature`, and creates deployments for `dev` and `production` environments
* The PR for `drews-feature` gets annotated with links to the active `dev` and `production` builds
* David publishes a branch called `davids-feature` to GitHub
* CI runs for the latest commit in `davids-feature`, and creates deployments for `dev` and `production` environments
* The PR for `davids-feature` gets annotated with links to the active `dev` and `production` builds
* The `dev` and `production` builds for `drews-feature` are marked as inactive

The 'inactive' builds are, in actual fact, still active. But because GitHub marks them as 'inactive', we don't get clickable hyperlinks for them.

Or to put it another way: the act of pushing to github causes a CI build to run, which has the side-effect of marking all existing deployments as inactive. The last deploy wins.

When I read about the [the `auto_inactive` property](https://docs.github.com/en/rest/reference/repos#inactive-deployments), I thought I had found a solution to this problem. I forked this repo, made the changes... 

I'm sorry to say that it appears to have made no difference whatsoever! 😞

**Comment by achambers** [comment]
Well hello there @nelstrom  and @dmcnamara-eng 👋 😄 

@nelstrom I was totally following you up until the point you said "I'm sorry to say that it appears to have made no difference whatsoever! 😞".

Are you saying that this PR actually doesn't make any difference to what you are experiencing?

**Comment by nelstrom** [comment]
@achambers yeah, I burried the lede there. Sorry!

Confirm, it makes no difference.

**Comment by achambers** [comment]
> @achambers yeah, I burried the lede there. Sorry!
> 
> Confirm, it makes no difference.

Soooo, are you needing me to do anything here are can this be closed?

**Comment by dmcnamara-eng** [comment]
Ok lads for clearing this up. I will close this.

Any excuse to annoy @achambers 😆

**Comment by achambers** [comment]
@dmcnamara-eng
> Ok lads for clearing this up. I will close this.
> 
> Any excuse to annoy @achambers 😆

Shall we meet in Rome to continue discussing this? :)

**Pull request closed without merging**
